services:
  app:
    build: .
    platform: linux/arm64
    image: trinket/app:latest
    ports:
      - 3000:3000
    container_name: trinket
    environment:
      NODE_ENV: development
      GOOGLE_CLOUD_PROJECT: demo-trinket
      FIRESTORE_EMULATOR_HOST: host.docker.internal:8080
      SESSION_PASSWORD: ${SESSION_PASSWORD}
      NODE_CONFIG: >-
        {"app":{"url":{"hostname":"localhost:3000","protocol":"http"}},"db":{"backend":"firestore","firestore":{"projectId":"demo-trinket"},"redis":{"enabled":false}}}
    networks:
      - trinket
networks:
  trinket:
    driver: bridge
